version: '3'

services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - POSTMAN_DOC=${POSTMAN_DOC}
      - JWT_SECRET=${JWT_SECRET}
    dns:
      - 8.8.8.8
